backend:
  name: github
  repo: coram-uk/coram-playbook
media_folder: "src/static/img"
public_folder: "/static/img"
publish_mode: 'editorial_workflow'

# Please run "npx @staticcms/proxy-server" for local backend
local_backend: false

# publish_mode: editorial_workflow
collections:
  - label: 'Projects, Topics, Authorities'
    name: 'recommendationsTopicsTags'
    files:
      - label: 'Topics Collection'
        name: 'topicsCollection'
        file: 'src/_data/topics.yml'
        fields:
          - label: 'Topics'
            name: 'topics'
            widget: 'list'
            summary: '{{fields.title}}'
            fields:
              - {
                  label: 'Title for url',
                  name: 'title',
                  widget: 'string',
                  hint: 'Use dashes (-) instead of spaces ( ) to separate words.',
                }
              - label: 'Hero'
                name: 'hero'
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'About Title', name: 'aboutTitle', widget: 'string', default: 'About this topic' }
              - { label: 'About Content', name: 'about', widget: 'markdown' }
              - { label: 'Why Title', name: 'whyTitle', widget: 'string', default: 'Why it matters' }
              - { label: 'Why Content', name: 'why', widget: 'markdown' }
              - { label: 'What Title', name: 'whatTitle', widget: 'string', default: 'What can we do' }
              - { label: 'What Content', name: 'what', widget: 'markdown' }
              - {
                  label: 'layout',
                  name: 'layout',
                  widget: 'hidden',
                  default: 'topic',
                }
      - name: 'projectsCollection'
        label: 'Projects Collection'
        file: 'src/_data/projects.yml'
        fields:
          - label: 'Projects'
            name: 'projects'
            widget: 'list'
            summary: '{{fields.title}}'
            fields:
              - {
                  label: 'Title for url',
                  name: 'title',
                  widget: 'string',
                  hint: 'Use dashes (-) instead of spaces ( ) to separate words.',
                }
              - {
                  label: 'Title for heading',
                  name: 'heading',
                  widget: 'string',
                }
              - { label: 'About Title', name: 'aboutTitle', widget: 'string', default: 'About this project', required: false }
              - {
                  label: 'About this project',
                  name: 'about',
                  widget: 'markdown',
                }
              - { label: 'Who Title', name: 'whoTitle', widget: 'string', default: 'Who is doing this', required: false }
              - label: "Who's doing this"
                name: 'who'
                widget: 'object'
                required: false
                fields:
                  - {
                      label: 'Authorities',
                      name: 'authorities',
                      collection: 'recommendationsTopicsTags',
                      widget: 'relation',
                      multiple: true,
                      display_fields: ['authorities.*'],
                      value_field: 'authorities.*',
                      search_fields: ['authorities.*'],
                      file: 'authorityCollection',
                      required: false,
                      options_length: 300,
                    }
                  - {
                      label: 'Map Image',
                      name: 'image',
                      widget: 'image',
                      media_folder: '../images/recommendations',
                      required: false,
                    }
                  - {
                      label: 'What are people doing',
                      name: 'what',
                      widget: 'markdown',
                      required: false,
                    }
      - label: 'Local Authorities'
        name: 'authorityCollection'
        file: 'src/_data/authority.yml'
        fields:
          - label: 'Authorities'
            name: 'authorities'
            widget: 'list'
            summary: '{{fields.name}}'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Main Page'
        name: 'index'
        file: 'src/_data/home.yml'
        fields:
          - label: 'Home'
            name: 'home'
            widget: 'object'
            fields:
              - label: 'Hero'
                name: 'hero'
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - {
                      label: 'Image',
                      name: 'image',
                      widget: 'image',
                      media_folder: '/src/images/heros',
                      allow_multiple: false,
                    }
                  - {
                      label: 'Image Alt Text',
                      name: 'imgAlt',
                      widget: 'string',
                    }
              - label: 'Topic Section'
                name: 'topicSection'
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'Content', name: 'content', widget: 'string' }
                  - { label: 'Button Text', name: 'buttontext', widget: 'string' }
                  - { label: 'Button URL', name: 'buttonurl', widget: 'string' }
                  - label: 'Topics'
                    name: 'topics'
                    widget: 'relation'
                    collection: 'recommendationsTopicsTags'
                    multiple: true
                    min: 1
                    max: 6
                    display_fields: ['topics.*.hero.title']
                    value_field: 'topics.*.title'
                    search_fields: ['topics.*.title', 'topics.*.hero.title']
                    file: 'topicsCollection'
              - label: 'Features'
                name: 'features'
                widget: 'object'
                fields:
                  - {
                      label: "What's new",
                      name: 'whatsNew',
                      widget: 'markdown',
                      required: false,
                    }
                  - label: 'Large Feature'
                    name: 'largeFeature'
                    widget: 'object'
                    fields:
                      - { label: 'Title', name: 'title', widget: 'string' }
                      - {
                          label: 'Content',
                          name: 'content',
                          widget: 'markdown',
                        }
                      - {
                          label: 'Image',
                          name: 'image',
                          widget: 'image',
                          media_folder: '../images/features',
                          allow_multiple: false,
                        }
                      - {
                          label: 'Image Alt Text',
                          name: 'imgAlt',
                          widget: 'string',
                        }
                      - { label: 'Link', name: 'link', widget: 'string' }
                      - { label: 'Link Text', name: 'linkText', widget: string }
                      - {
                          label: 'Layout',
                          name: 'layout',
                          widget: 'hidden',
                          default: 'lg',
                        }
                  - label: 'Small Features'
                    name: 'smallFeature'
                    widget: 'list'
                    fields:
                      - { label: 'Title', name: 'title', widget: 'string' }
                      - {
                          label: 'Content',
                          name: 'content',
                          widget: 'markdown',
                        }
                      - {
                          label: 'Image',
                          name: 'image',
                          widget: 'image',
                          media_folder: '/src/images/features',
                          allow_multiple: false,
                        }
                      - {
                          label: 'Image Alt Text',
                          name: 'imgAlt',
                          widget: 'string',
                        }
                      - { label: 'Link', name: 'link', widget: 'string' }
              - label: 'Our mission'
                name: 'mission'
                widget: 'object'
                fields:
                  - { label: 'Title', name: 'title', widget: 'string' }
                  - { label: 'Content', name: 'content', widget: 'markdown' }
                  - {
                      label: 'Image',
                      name: 'image',
                      widget: 'image',
                      media_folder: '../images/heros',
                      allow_multiple: false,
                    }
                  - {
                      label: 'Image Alt Text',
                      name: 'imgAlt',
                      widget: 'string',
                    }
                  - {
                      label: 'Background Color',
                      name: 'backgroundColor',
                      widget: 'hidden',
                      default: 'light',
                    }
      - label: 'About Page'
        name: 'about'
        file: 'src/_data/about.yml'
        fields:
          - label: 'Hero'
            name: 'hero'
            widget: 'object'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - {
                  label: 'Image',
                  name: 'image',
                  widget: 'image',
                  media_folder: '/src/images/heros',
                  required: false,
                  allow_multiple: false,
                }
              - {
                  label: 'Image Alt Text',
                  name: 'imgAlt',
                  widget: 'string',
                  required: false,
                }
          - label: 'About'
            name: 'about'
            widget: 'markdown'
  - name: 'sections'
    label: 'Sections'
    files:
      - label: 'Header'
        name: 'header'
        file: 'src/_data/header.yml'
        fields:
          - { label: 'Logo', name: 'logo', widget: 'image', media_folder: '/src/images', required: true, allow_multiple: false }
          - label: 'Menu'
            name: 'menu'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'URL', name: 'url', widget: 'string' }
              - { label: 'Icon', name: 'icon', widget: 'image', media_folder: '/src/images/icons', required: true, allow_multiple: false }
      - label: 'Topics Index'
        name: 'topicsIndex'
        file: 'src/_data/topicsIndex.yml'
        fields:
          - { label: 'Hero', name: 'hero', widget: 'image', media_folder: '/src/images', required: true, allow_multiple: false }
          - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Projects Index'
        name: 'projectsIndex'
        file: 'src/_data/projectsIndex.yml'
        fields:
          - { label: 'Hero', name: 'hero', widget: 'image', media_folder: '/src/images', required: true, allow_multiple: false }
          - { label: 'Title', name: 'title', widget: 'string' }
      - label: 'Footer'
        name: 'footer'
        file: 'src/_data/footer.yml'
        fields:
          - { label: 'Address', name: 'address', widget: 'string' }
          - { label: 'Copyright', name: 'copyright', widget: 'string' }
          - { label: 'Nav Title', name: 'navtitle', widget: 'string' }
          - label: 'Nav Links'
            name: 'navLinks'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'URL', name: 'url', widget: 'string' }
          - { label: 'Social Title', name: 'socialtitle', widget: 'string' }
          - label: 'Social Links'
            name: 'socialLinks'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'URL', name: 'url', widget: 'string' }
              - { label: 'Icon', name: 'icon', widget: 'image', media_folder: '/src/images/social-icons', required: true, allow_multiple: false }
